site_name: Choru's Tech Wiki
site_url: https://choru-k.github.io/choru-wiki/
site_author: choru
site_description: Computer Science, DevOps, and System Programming Knowledge Base

theme:
  name: material
  language: en
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  font:
    text: Roboto
    code: Roboto Mono

  features:
    # Navigation
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.prune
    - navigation.indexes
    - navigation.top
    - navigation.footer
    # Table of contents
    - toc.follow
    # Search
    - search.highlight
    - search.share
    - search.suggest
    # Content
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - content.tabs.link
    - content.tooltips
    - content.action.edit
    - content.action.view
    # Header
    - header.autohide
    - announce.dismiss

markdown_extensions:
  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
      title: Table of Contents
  - tables

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: choru-k
      repo: choru-wiki
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
      lang:
        - en
        - ko
  - tags:
      tags_file: tags.md
  # Optional: Blog plugin for future use
  # - blog:
  #     blog_dir: blog
  #     post_date_format: full
  #     archive_date_format: MMMM yyyy
  #     categories_allowed:
  #       - DevOps
  #       - Programming
  #       - System

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/choru-k
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/choru

  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback! Help us improve this page by
            using our <a href="..." target="_blank" rel="noopener">feedback form</a>.

  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.

# Extra JavaScript for LaTeX support
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# Extra CSS for custom styling
extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - Computer Science:
      - cs/index.md
      - CS Mastery Guide:
          - cs/guide/index.md
          - "Chapter 1: Process & Thread":
              - "Overview": cs/guide/chapter-01-process-thread/index.md
          - "Chapter 2: CPU & Interrupt":
              - "Overview": cs/guide/chapter-02-cpu-interrupt/index.md
          - "Chapter 3: Memory System":
              - "Overview": cs/guide/chapter-03-memory-system/index.md
          - "Chapter 4: System Call & Kernel":
              - "Overview": cs/guide/chapter-04-syscall-kernel/index.md
          - "Chapter 5: Compiler & Linker":
              - "Overview": cs/guide/chapter-05-compiler-linker/index.md
          - "Chapter 6: File I/O":
              - "Overview": cs/guide/chapter-06-file-io/index.md
          - "Chapter 7: Network Programming":
              - "Overview": cs/guide/chapter-07-network-programming/index.md
          - "Chapter 8: Memory Allocator & GC":
              - "Overview": cs/guide/chapter-08-memory-allocator-gc/index.md
          - "Chapter 9: Advanced Memory Management":
              - "Overview": cs/guide/chapter-09-advanced-memory-management/index.md
          - "Chapter 10: Async Programming":
              - "Overview": cs/guide/chapter-10-async-programming/index.md
          - "Chapter 11: Performance Optimization":
              - "Overview": cs/guide/chapter-11-performance-optimization/index.md
          - "Chapter 12: Observability & Debugging":
              - "Overview": cs/guide/chapter-12-observability-debugging/index.md
          - "Chapter 13: Container & Kubernetes":
              - "Overview": cs/guide/chapter-13-container-kubernetes/index.md
          - "Chapter 14: Distributed Systems":
              - "Overview": cs/guide/chapter-14-distributed-systems/index.md
          - "Chapter 15: Microservices Architecture":
              - "Overview": cs/guide/chapter-15-microservices-architecture/index.md
          - "Chapter 16: Distributed System Patterns":
              - "Overview": cs/guide/chapter-16-distributed-system-patterns/index.md
          - "Chapter 17: Security Engineering":
              - "Overview": cs/guide/chapter-17-security-engineering/index.md
          - "Learning Paths":
              - "Overview": cs/guide/learning-paths/README.md
              - "Fundamentals":
                  - "Main": cs/guide/learning-paths/fundamentals/README.md
                  - "Application Development": cs/guide/learning-paths/fundamentals/application-development/README.md
                  - "System Programming": cs/guide/learning-paths/fundamentals/system-programming/README.md
                  - "Infrastructure": cs/guide/learning-paths/fundamentals/infrastructure/README.md
                  - "Distributed Systems": cs/guide/learning-paths/fundamentals/distributed-systems/README.md
              - "Intermediate":
                  - "Main": cs/guide/learning-paths/intermediate/README.md
                  - "Application Development": cs/guide/learning-paths/intermediate/application-development/README.md
                  - "System Programming": cs/guide/learning-paths/intermediate/system-programming/README.md
                  - "Infrastructure": cs/guide/learning-paths/intermediate/infrastructure/README.md
                  - "Network Programming": cs/guide/learning-paths/intermediate/network-programming/README.md
                  - "Distributed Systems": cs/guide/learning-paths/intermediate/distributed-systems/README.md
              - "Advanced":
                  - "Main": cs/guide/learning-paths/advanced/README.md
                  - "Application Development": cs/guide/learning-paths/advanced/application-development/README.md
                  - "System Programming": cs/guide/learning-paths/advanced/system-programming/README.md
                  - "Infrastructure": cs/guide/learning-paths/advanced/infrastructure/README.md
                  - "Distributed Systems": cs/guide/learning-paths/advanced/distributed-systems/README.md
      - Memory Management:
          - cs/memory/index.md
          - Process Memory Structure: cs/memory/process-memory-structure.md
          - Virtual Memory & Page Table: cs/memory/virtual-memory-page-table.md
          - Multithread Stack Memory: cs/memory/multithread-stack-memory.md
          - Page Cache Mechanism: cs/memory/page-cache.md
          - JVM Memory & GC: cs/memory/jvm-memory-gc.md
          - PSI Memory Monitoring: cs/memory/psi-monitoring.md
          - Garbage Collection Basics: cs/memory/garbage-collection-basics.md
          - Cgroup & Container Memory: cs/memory/cgroup-container-memory.md
          - Language Memory Management: cs/memory/language-memory-management.md
          - OOM Killer: cs/memory/oom-killer.md
      - Process & Thread:
          - cs/process/index.md
          - "Process vs Thread #1: Linux Clone": cs/process/process-vs-thread-1.md
          - "Process vs Thread #2: Memory Sharing": cs/process/process-vs-thread-2.md
          - "Process vs Thread #3: Scheduling": cs/process/process-vs-thread-3.md
          - "Linux Scheduling #1: Basics": cs/process/linux-scheduling-1.md
          - "Linux Scheduling #2: CFS": cs/process/linux-scheduling-2.md
          - "Linux Interrupt #1: Fundamentals": cs/process/linux-interrupt-1.md
          - "Linux Interrupt #2: ksoftirqd": cs/process/linux-interrupt-2.md
          - "Linux Interrupt #3: Timer & CPU Isolation": cs/process/linux-interrupt-3.md
      - Programming:
          - cs/programming/index.md
          - Callback Functions: cs/programming/callback.md
          - Coroutines: cs/programming/coroutine.md
          - "Event Loop: Single-threaded Concurrency Magic": cs/programming/event-loop.md
      - Network Programming:
          - cs/network/index.md
          - Socket Programming: cs/network/socket.md
          - "epoll: Linux High-Performance I/O Multiplexing": cs/network/epoll.md
      - Compilation:
          - cs/compilation/index.md
          - "Compilation Guide: From Source to Binary": cs/compilation/compile.md
          - "Linker: Symbol Resolution to LTO": cs/compilation/linker.md
          - Header Files & Preprocessing: cs/compilation/header-files.md
          - Symbol Table: cs/compilation/symbol-table.md
          - Static Libraries: cs/compilation/static-library.md
          - Dynamic Libraries: cs/compilation/dynamic-library.md
      - System Programming:
          - cs/system/index.md
          - File Descriptors: cs/system/file-descriptor.md
      - AWS Internals (Storytelling):
          - cs/aws-internals/index.md
          - S3 Deep Dive:
              - cs/aws-internals/s3/index.md
              - "Data Durability: 99.999999999% Magic": cs/aws-internals/s3/01-architecture.md
              - "Consistency: From Eventual to Strong": cs/aws-internals/s3/02-storage-classes.md
              - "Performance: Netflix's Christmas Story": cs/aws-internals/s3/03-performance.md
              - "Security: Capital One Breach Timeline": cs/aws-internals/s3/04-security.md
          - Load Balancing:
              - cs/aws-internals/load-balancing/index.md
              - "ELB/ALB: Black Friday Crisis Management": cs/aws-internals/load-balancing/01-elb-alb.md
              - "NLB/GWLB: Fortnite's 100M Concurrent Users": cs/aws-internals/load-balancing/02-nlb-gwlb.md
              - "Algorithms: Instagram's 10B User Distribution": cs/aws-internals/load-balancing/03-algorithms.md
          - Networking:
              - cs/aws-internals/networking/index.md
              - "VPC: Netflix's 200Gbps Virtual Network": cs/aws-internals/networking/01-vpc.md
              - "Route 53: Spotify's 0.001s DNS Magic": cs/aws-internals/networking/02-route53.md
              - "CloudFront: Disney+'s Global Edge Network": cs/aws-internals/networking/03-cloudfront.md
              - "Direct Connect: JP Morgan's 0.001s Trading": cs/aws-internals/networking/04-directconnect.md
          - Compute:
              - cs/aws-internals/compute/index.md
              - "EC2 Nitro: Netflix's 400Gbps Streaming": cs/aws-internals/compute/01-ec2-nitro.md
              - "Lambda: Duolingo's 100M Users Secret": cs/aws-internals/compute/02-lambda.md
              - "ECS: Pinterest's 10B Images Serving": cs/aws-internals/compute/03-ecs.md
              - "EKS: Airbnb's 5000 Microservices": cs/aws-internals/compute/04-eks.md
          - Database:
              - cs/aws-internals/database/index.md
              - "RDS: Shopify's Black Friday Survival": cs/aws-internals/database/01-rds.md
              - "DynamoDB: Lyft's 10B Rides Challenge": cs/aws-internals/database/02-dynamodb.md
              - "Aurora: Netflix's Cloud-Native Revolution": cs/aws-internals/database/03-aurora.md
              - "ElastiCache: Twitter's Microsecond World": cs/aws-internals/database/04-elasticache.md
          - CloudFront CDN:
              - cs/aws-internals/cloudfront/index.md
              - "Architecture: Disney+'s 450 Edge Locations": cs/aws-internals/cloudfront/01-architecture.md
              - "Optimization: TikTok's Viral Challenge": cs/aws-internals/cloudfront/02-optimization.md
      - Kubernetes Deep Dive (Storytelling):
          - cs/kubernetes/index.md
          - Architecture:
              - cs/kubernetes/architecture/index.md
              - "Overview: Google's 2B Containers Secret": cs/kubernetes/architecture/01-overview.md
              - "API Server: Cloudflare's DDoS Defense": cs/kubernetes/architecture/02-api-server.md
              - "etcd: Discord's 1B Messages Recovery": cs/kubernetes/architecture/03-etcd.md
          - Workloads:
              - cs/kubernetes/workloads/index.md
              - "Pods: Airbnb's 10K Bookings/sec": cs/kubernetes/workloads/01-pods.md
              - "Controllers: Kubernetes' Self-healing Systems": cs/kubernetes/workloads/02-controllers.md
              - "StatefulSets: Persistent Workload Management": cs/kubernetes/workloads/03-statefulsets.md
              - "DaemonSets: Node-level System Services": cs/kubernetes/workloads/04-daemonsets.md
          - Networking:
              - cs/kubernetes/networking/index.md
              - "Cluster Networking: Shopify's Pod Communication": cs/kubernetes/networking/01-cluster-networking.md
              - "Services: Netflix's Load Balancing": cs/kubernetes/networking/02-services.md
              - "Ingress: GitHub Pages' Traffic Routing": cs/kubernetes/networking/03-ingress.md
              - "CNI Plugins: Discord's Network Performance": cs/kubernetes/networking/04-cni-plugins.md
          - Storage:
              - cs/kubernetes/storage/index.md
              - "Volumes: Spotify's Data Persistence": cs/kubernetes/storage/01-volumes.md
              - "Persistent Volumes: Uber's Stateful Apps": cs/kubernetes/storage/02-persistent-volumes.md
              - "CSI Drivers: Netflix's Storage Integration": cs/kubernetes/storage/03-csi-drivers.md
          - Scaling:
              - cs/kubernetes/scaling/index.md
              - "HPA: Target's Black Friday Autoscaling": cs/kubernetes/scaling/01-hpa.md
              - "VPA: Spotify's Resource Optimization": cs/kubernetes/scaling/02-vpa.md
              - "Cluster Autoscaler: Airbnb's Dynamic Infrastructure": cs/kubernetes/scaling/03-cluster-autoscaler.md
  - DevOps:
      - Service Mesh:
          - Istio Traffic Interception: devops/istio-traffic-interception.md
      - Container:
          - Dockerfile Best Practices: devops/dockerfile-best-practices.md
      - Kubernetes:
          - EKS LoadBalancer Modes: devops/eks-lb-modes.md
          - Pod Debugging: devops/kubernetes/pod-debugging.md
          - Graceful Shutdown with Istio: devops/kubernetes/graceful-shutdown-istio.md
      - Monitoring:
          - Prometheus Kubernetes CPU Metrics: devops/monitoring/prometheus-kubernetes-cpu-metrics.md
      - Performance:
          - CPU Usage Analysis: devops/performance/cpu-usage-analysis.md
      - Debugging:
          - ptrace System Call Internals: devops/debugging/ptrace-internals.md
          - GDB Advanced Debugging: devops/debugging/gdb-advanced-debugging.md
          - strace System Call Analysis: devops/debugging/strace-debugging.md
          - Python Library Analysis (so/nm): devops/debugging/python-library-analysis-so-nm.md
          - Docker Exit 137 Debugging: devops/debugging/docker-exit-137-debugging.md
  - Database:
      - RDS:
          - Auto Increment Strategy: db/rds-auto-increment.md
      - ProxySQL:
          - ProxySQL Overview: devops/proxysql.md
          - Connection Pooling Issues: db/proxysql-connection-pooling.md
          - Load Test Troubleshooting: db/proxysql-loadtest-issue.md
  - Algorithms:
      - LeetCode:
          - algorithms/leetcode/index.md
          - Study Methodology: algorithms/leetcode/methodology.md
          - Problems by Pattern: algorithms/leetcode/patterns.md
          - Problems by Topic: algorithms/leetcode/topics.md
  - Machine Learning:
      - ml/index.md
      - Policy Gradient:
          - REINFORCE: ml/reinforce.md
          - Actor Critic: ml/actor-critic.md
          - A2C: ml/a2c.md
          - GAE: ml/gae.md
          - TNPG: ml/tnpg.md
      - Deep Q-Network:
          - Double DQN: ml/double-dqn.md
          - Duel DQN: ml/duel-dqn.md
          - Noisy Net: ml/noisy-net.md
          - Prioritized Experience Replay: ml/prioritized-experience-replay.md
      - Advanced Methods:
          - Rainbow: ml/rainbow.md
          - Rainbow Distributional: ml/rainbow-distributional.md
  - Tags: tags.md
  - Demo:
    - demo.md
    - demo-mermaid.md
